---
- name: Crear grupo GProfesores
  group:
    name: GProfesores
    state: present

- name: Crear grupo GAlumnos
  group:
    name: GAlumnos
    state: present

- name: Crear usuario profesor y agregar a GProfesores
  user:
    name: profesor
    groups: GProfesores
    state: present

- name: Crear usuario alumno y agregar a GAlumnos
  user:
    name: alumno
    groups: GAlumnos
    state: present

